### ISSUE TITLE
Allow parseContent to handle augmented JSON media types

### ISSUE THREAD

**Issue by briancavalier** [mjackson/mach#48]
I was prototyping something today where I needed to send JSON Patch from the client to the server (actually in both directions).  JSON Patch is represented as JSON, but [the prescribed media type is `application/json-patch+json`](https://tools.ietf.org/html/rfc6902#section-3).  So, it gets skipped by [the exact string compare in `Message.prototype.parseContent`](https://github.com/mjackson/mach/blob/master/modules/Message.js#L210)

There are other augmented JSON media types out there as well, such as [HAL](http://stateless.co/hal_specification.html), which uses `application/hal+json`.

Could the check be loosened to match something like `/^application\/(\S+[+])?json)$/`? 

This seems like a very simple change in master, but I want to see what you think, and also make sure this isn't already being done.  I'd be happy to submit a PR if it sounds like a good change.  Thanks!

**Comment by mjackson** [comment]
Hey @briancavalier ! I just pushed a few commits that make it a lot easier to extend mach with your own custom parsers. Essentially, you need to do this:

```js
var mach = require('mach');

mach.Message.PARSERS['application/json+patch'] = function (message, maxLength, uploadPrefix) {
  // parse your message here and return a hash (or a promise for a hash) of parameters
  // in the content body.
};
```

mach's own internal parsers are implemented using this mechanism. Check out the parsers for:

- [application/json](https://github.com/mjackson/mach/blob/8fecac88d6d08c793b6287911a66960ec0b840aa/modules/Message.js#L47-L49)
- [application/x-www-form-urlencoded](https://github.com/mjackson/mach/blob/8fecac88d6d08c793b6287911a66960ec0b840aa/modules/Message.js#L51-L53)
- [multipart/form-data](https://github.com/mjackson/mach/blob/8fecac88d6d08c793b6287911a66960ec0b840aa/modules/extensions/multipart.js#L8-L21)

The first two simply buffer the content stream and parse it in one shot, but the multipart parser uses a streaming parser to avoid buffering large files.

Just let me know if you have any questions! :)
