### ISSUE TITLE
Mach 1.0.0 GM breaks webpack

### ISSUE THREAD

**Issue by appsforartists** [mjackson/mach#63]
Looks like something server-side is being required in the client version of 1.0.0:

```
ERROR in ./~/mach/modules/extensions/fs.js
Module not found: Error: Cannot resolve module 'fs' in /Users/bresimpson/Projects/ambidex-example/node_modules/mach/modules/extensions
 @ ./~/mach/modules/extensions/fs.js 3:9-22

ERROR in ./~/mach/modules/utils/streamPartToDisk.js
Module not found: Error: Cannot resolve module 'fs' in /Users/bresimpson/Projects/ambidex-example/node_modules/mach/modules/utils
 @ ./~/mach/modules/utils/streamPartToDisk.js 3:9-22

ERROR in ./~/mach/modules/middleware/file.js
Module not found: Error: Cannot resolve module 'fs' in /Users/bresimpson/Projects/ambidex-example/node_modules/mach/modules/middleware
 @ ./~/mach/modules/middleware/file.js 3:9-22

ERROR in ./~/mach/modules/utils/getFileStats.js
Module not found: Error: Cannot resolve module 'fs' in /Users/bresimpson/Projects/ambidex-example/node_modules/mach/modules/utils
 @ ./~/mach/modules/utils/getFileStats.js 3:9-22

ERROR in ./~/mach/modules/utils/generateIndex.js
Module not found: Error: Cannot resolve module 'fs' in /Users/bresimpson/Projects/ambidex-example/node_modules/mach/modules/utils
 @ ./~/mach/modules/utils/generateIndex.js 3:9-22
```

1.0.0-rc4 worked fine.

**Comment by mjackson** [comment]
@appsforartists Hmm, it sounds like you're getting files in your webpack build that you're not supposed to be getting. For the global build [we use](https://github.com/mjackson/mach/blob/master/webpack.config.js#L18-L21):

```js
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
      'typeof window': JSON.stringify('object')
    })
```

This plugin lets us filter out files that aren't supposed to be part of the webpack build. It's standard config that I use in all my webpack builds, so it slipped past my radar. The mach codebase uses `typeof window` in several places to filter out code that should/shouldn't run in the browser.

I could add some "how to build with webpack" docs somewhere that explain this caveat. I can't really think of a better way to resolve the problem right now. You?

**Comment by appsforartists** [comment]
I've flirted with adding an `IN_BROWSER` constant (to do effectively what you're doing with `typeof window`), but haven't needed to do so yet.  I have my Webpack set up to replace any files that contain `.server.` with `.client.`, following a convention I saw used in various Webpack issues.  That's worked well-enough for me to deal with server-only code in files I'd otherwise need to import from the client too.

Forcing a `typeof window` definition isn't horrible, but it would be great if it worked out-of-the-box (and it did in RC4).  Do you know what's changed in the last couple days that would have triggered this?

**Comment by mjackson** [comment]
I'm pretty sure the breakage was caused by switching to use `typeof window` as a browser check instead of using package.json's `browser` field to simply load a different file.

It seems like using the `browser` field is the way to go though, since all the major bundlers respect it. I'll make a fix.

**Comment by appsforartists** [comment]
:+1:
