### ISSUE TITLE
Feature request: mapper.unmap

### ISSUE THREAD

**Issue by appsforartists** [mjackson/mach#64]
It would be good for symmetry to be able to `unmap` anything you can `map`.

**Comment by mjackson** [comment]
Mappers (and stacks, routers, etc.) aren't really supposed to be things that you manipulate after you set them up. In fact, I've been tossing around a few ideas in my head for a more declarative interface to building apps. The idea is that if you declare everything up front, mach has a chance to optimize it. If you can change stuff later, it's much more difficult to optimize.

Is there a particular use case you're after? i.e. can you explain in a non-technical way what you want your app to accomplish?

**Comment by appsforartists** [comment]
It was just an idea I had that I wanted to jot down while it was still in my head.  I was thinking about what would happen if you had a route that was mapped to a particular baseURL, and you wanted to move that mapping to a mapper higher in the tree.  (Unmap the old and remap the new seemed like it could work.)

Now that I think about it more closely, I realize that the first map (at least for my purposes) would probably happen in `stack.route`, so I could accomplish the same thing without needing to change the API.
